# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: counter/counter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'counter/counter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ounter/counter.proto\x12\x07\x63ounter\"\x0e\n\x0c\x43ountRequest\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32M\n\x0e\x43ounterService\x12;\n\x08GetCount\x12\x15.counter.CountRequest\x1a\x16.counter.CountResponse\"\x00\x42\x15H\x01Z\x11\x63ounter/counterpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'counter.counter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001Z\021counter/counterpb'
  _globals['_COUNTREQUEST']._serialized_start=34
  _globals['_COUNTREQUEST']._serialized_end=48
  _globals['_COUNTRESPONSE']._serialized_start=50
  _globals['_COUNTRESPONSE']._serialized_end=80
  _globals['_COUNTERSERVICE']._serialized_start=82
  _globals['_COUNTERSERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
